### ISSUE TITLE
How to get the val_boxes.txt

### ISSUE THREAD

**Issue by ChunmengLiu1** [zhiweichen0012/LCTR#4]
Hi! thank you for the good job!
I find your test/val_boxes.txt is different from the official CUB dataset provided. Can you share it with me? my email is lcm@tongji.edu.cn. Thanks!

**Comment by zhiweichen0012** [comment]
Thank you very much for your interest in our work! And sorry for the late reply.

To make it easier to read the data, we simply add the image path at the top of each line compared to the official file. To facilitate your research, I have sent the file to your e-mail, please pay attention to receive.

Have a nice day~
